events {}

http {
    upstream auth_service {
        server auth-service:5000;
    }

    upstream weather_service {
        server weather-service:5000;
    }

    upstream calendar_service {
        server calendar-service:5000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /weather/ {
            proxy_pass http://weather_service/;
        }

        location /calendar/ {
            proxy_pass http://calendar_service/;
        }
    }
}
